version: '3.7'
services:
  streamlit:
    build:
      context: streamlit/.
    hostname: streamlit
    restart: always
    container_name: streamlit
    ports:
      - 8501:8501
    env_file:
      - .env